<a href="https://colab.research.google.com/github/tankTopTaro/TensorFlow-Colab-Notebooks/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.17.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [8]:
# Create a matrix
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
another_matrix = tf.constant([[10.,7.], [3., 2.], [8., 9.]], dtype=tf.float16)  # specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

### Creating tensors with tf.Variable

In [15]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [18]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [19]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

In [27]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [29]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

not_shuffled.ndim, not_shuffled

(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>)

In [32]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [33]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

### Exercise Generate 5 random tensors

In [41]:
rand_1 = tf.random.Generator.from_seed(42, alg="threefry")
rand_2 = tf.random.Generator.from_seed(5).normal(shape=(10, 7))
rand_3 = tf.random.Generator.from_seed(100).normal(shape=(3, 2))
rand_4 = tf.random.Generator.from_seed(1234).normal(shape=(2, 3))
rand_5 = tf.random.Generator.from_seed(123, alg="philox")

print("Rand_1", rand_1, "\nRand_2", rand_2,
      "\nRand_3", rand_3, "\nRand_4", rand_4,
      "\nRand_5", rand_5)

Rand_1 <tensorflow.python.ops.stateful_random_ops.Generator object at 0x79f36ff2e9b0> 
Rand_2 tf.Tensor(
[[ 1.0278524   0.27974114 -0.01347923  1.845181    0.97061104 -1.0242516
  -0.6544423 ]
 [-0.29738766 -1.3240396   0.28785667 -0.8757901  -0.08857018  0.69211644
   0.84215707]
 [-0.06378496  0.92800784 -0.6039789  -0.1766927   0.04221033  0.29037967
  -0.29604465]
 [-0.21134205  0.01063002  1.5165398   0.27305737 -0.29925638 -0.3652325
   0.61883307]
 [-1.0130816   0.28291714  1.2132233   0.46988967  0.37944323 -0.6664026
   0.6054596 ]
 [ 0.19181173  0.8045827   0.4769051  -0.7812124  -0.996891    0.33149973
  -0.5445254 ]
 [ 1.5222508   0.59303206 -0.63509274  0.3703566  -1.0939722  -0.4601445
   1.5420506 ]
 [-0.16822556 -0.4390865  -0.4129243   0.35877243 -1.9095894  -0.2094769
   0.8286217 ]
 [-0.06695071 -0.35105535  1.0884082  -1.3863064   0.88051325 -1.6833194
   0.86754173]
 [-0.19625713 -1.322665   -0.02279496 -0.1383193   0.44207528 -0.7531523
   2.0261486 ]], shape=(10,

In [45]:
tf.random.shuffle(rand_3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.08036723, -1.7199678 ],
       [-0.4188493 ,  0.29532313],
       [-0.90112925, -0.0175216 ]], dtype=float32)>

In [46]:
tf.random.shuffle(rand_4, seed=42)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.5061547 ,  1.3169702 ,  0.7137579 ],
       [ 0.9356609 ,  1.0854305 , -0.93788373]], dtype=float32)>